services:
  app:
    build: .
    container_name: parqueadero-backend
    restart: on-failure
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/${MYSQL_DATABASE}
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - parqueadero-net

  mysql:
    image: mysql:8.0
    container_name: mysql-parqueadero
    ports:
      - "3310:3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - parqueadero-net

volumes:
  mysql_data:

networks:
  parqueadero-net: